### ISSUE TITLE
Computer Won't Stop Inputting "=" Upon Initialising PikaDJ

### ISSUE THREAD

**Issue by Kijimi** [Silvea12/PikaDJ#3]
Hi, 
I find that whenever I execute PikaDJ via "./PikaDJ", my computer begins to input "=" in any typeable space it can. In console, it says that the config is reloaded, initialised, then reloaded once more before chaos ensues. I followed the installation guide as follows and it went smoothly for the most part.

**Comment by Silvea12** [comment]
It is doing this trying to detect TF2. Make sure the game is running when you try to do this. Also make sure the log file is being written to.

Please note that I do not really develop this software anymore, so there is a chance it may not be compatible with current versions of TF2 due to engine updates breaking things (it's happened before). I've since worked on some better versions of this software in my spare time, and may release one of the versions in future. One that isn't quite as janky as this one.

Sent from ProtonMail mobile

-------- Original Message --------
